//constants enums and Maps file

export  class AchCEMs {

    public static readonly serviceClassCodes: Map<number, string> = new Map([
        [200, 'ACH Entries Mixed Debits and Credits'],
        [220, 'ACH Credits Only'],
        [225, 'ACH Debits Only']
      ]);

    public static readonly transactionCodes: Map<number, string> = new Map([
        [22, 'Deposit destined for a Checking Account'],
        [23, 'Prenotification for a checking credit'],
        [24, 'Zero dollar with remittance into Checking Account'],
        [27, 'Debit destined for a Checking Account'],
        [28, 'Prenotification for a checking debit'],
        [29, 'Zero dollar with remittance into Checking Account'],
        [32, 'Deposit destined for a Savings Account'],
        [33, 'Prenotification for a savings credit'],
        [34, 'Zero dollar with remittance into Savings Account'],
        [37, 'Debit destined for a Savings Account'],
        [38, 'Prenotification for a Savings debit'],
        [39, 'Zero dollar with remittance into Savings Account']
      ]); 

      public static readonly serviceEntryClassDescriptions: Map<string, string> = new Map([
        ["ACK", "Acknowledgment Entry"],
        ["ADV", "Automated Accounting Advice"],
        ["ARC", "Accounts Receivable Entry"],
        ["ATX", "Financial EDI Acknowledgment"],
        ["BOC", "Back Office Conversion"],
        ["CBR", "Cross Border Entry"],
        ["CCD", "Cash Concentration and Disbursement"],
        ["CIE", "Customer Initiated Entry"],
        ["COR", "Automated Notification of Change"],
        ["CTX", "Corporate Trade Exchange"],
        ["DNE", "Death Notification Entry"],
        ["ENR", "Automated Enrollment Entry"],
        ["IAT", "International"],
        ["MTE", "Machine Transfer Entry"],
        ["PBR", "Cross Border Entry"],
        ["POP", "Point-of-Purchase Entry"],
        ["POS", "Point-of-Sale Entry"],
        ["PPD", "Prearranged Payment and Deposit"],
        ["RCK", "Re-presented Check Entry"],
        ["SHR", "Shared Network Transaction"],
        ["TEL", "Telephone-Initiated Entry"],
        ["TRC", "Truncated Check Entry"],
        ["TRX", "Truncated Entries Exchange"],
        ["WEB", "Internet-Initiated Entry"],
        ["XCK", "Destroyed Check Entry"]
    ]);

    public static readonly foreignExchangeIndicatorDescriptions: Map<string, string> = new Map([
      ["FV", "Fixed-to-Variable"],
      ["FF", "Fixed-to-Fixed"],
      ["VF", "Variable-to-Fixed"]
    ]);


    public static readonly isoCountryCodeNames: Map<string, string> = new Map([
      ["AD", "Andorra"], 
      ["AE", "United Arab Emirates"], 
      ["AF", "Afghanistan"], 
      ["AG", "Antigua and Barbuda"], 
      ["AI", "Anguilla"], 
      ["AL", "Albania"], 
      ["AM", "Armenia"], 
      ["AO", "Angola"], 
      ["AQ", "Antarctica"], 
      ["AR", "Argentina"], 
      ["AS", "American Samoa"], 
      ["AT", "Austria"], 
      ["AU", "Australia"], 
      ["AW", "Aruba"], 
      ["AX", "Ã…land Islands"], 
      ["AZ", "Azerbaijan"], 
      ["BA", "Bosnia and Herzegovina"], 
      ["BB", "Barbados"], 
      ["BD", "Bangladesh"], 
      ["BE", "Belgium"], 
      ["BF", "Burkina Faso"], 
      ["BG", "Bulgaria"], 
      ["BH", "Bahrain"], 
      ["BI", "Burundi"], 
      ["BJ", "Benin"], 
      ["BL", "Saint BarthÃ©lemy"], 
      ["BM", "Bermuda"], 
      ["BN", "Brunei Darussalam"], 
      ["BO", "Bolivia, Plurinational State of"], 
      ["BQ", "Bonaire, Sint Eustatius and Saba"], 
      ["BR", "Brazil"], 
      ["BS", "Bahamas"], 
      ["BT", "Bhutan"], 
      ["BV", "Bouvet Island"], 
      ["BW", "Botswana"], 
      ["BY", "Belarus"], 
      ["BZ", "Belize"], 
      ["CA", "Canada"], 
      ["CC", "Cocos (Keeling) Islands"], 
      ["CD", "Congo, Democratic Republic of the"], 
      ["CF", "Central African Republic"], 
      ["CG", "Congo"], 
      ["CH", "Switzerland"], 
      ["CI", "CÃ´te d'Ivoire"], 
      ["CK", "Cook Islands"], 
      ["CL", "Chile"], 
      ["CM", "Cameroon"], 
      ["CN", "China"], 
      ["CO", "Colombia"], 
      ["CR", "Costa Rica"], 
      ["CU", "Cuba"], 
      ["CV", "Cabo Verde"], 
      ["CW", "CuraÃ§ao"], 
      ["CX", "Christmas Island"], 
      ["CY", "Cyprus"], 
      ["CZ", "Czechia"], 
      ["DE", "Germany"], 
      ["DJ", "Djibouti"], 
      ["DK", "Denmark"], 
      ["DM", "Dominica"], 
      ["DO", "Dominican Republic"], 
      ["DZ", "Algeria"], 
      ["EC", "Ecuador"], 
      ["EE", "Estonia"], 
      ["EG", "Egypt"], 
      ["EH", "Western Sahara"], 
      ["ER", "Eritrea"], 
      ["ES", "Spain"], 
      ["ET", "Ethiopia"], 
      ["FI", "Finland"], 
      ["FJ", "Fiji"], 
      ["FK", "Falkland Islands (Malvinas)"], 
      ["FM", "Micronesia, Federated States of"], 
      ["FO", "Faroe Islands"], 
      ["FR", "France"], 
      ["GA", "Gabon"], 
      ["GB", "United Kingdom of Great Britain and Northern Ireland"], 
      ["GD", "Grenada"], 
      ["GE", "Georgia"], 
      ["GF", "French Guiana"], 
      ["GG", "Guernsey"], 
      ["GH", "Ghana"], 
      ["GI", "Gibraltar"], 
      ["GL", "Greenland"], 
      ["GM", "Gambia"], 
      ["GN", "Guinea"], 
      ["GP", "Guadeloupe"], 
      ["GQ", "Equatorial Guinea"], 
      ["GR", "Greece"], 
      ["GS", "South Georgia and the South Sandwich Islands"], 
      ["GT", "Guatemala"], 
      ["GU", "Guam"], 
      ["GW", "Guinea-Bissau"], 
      ["GY", "Guyana"], 
      ["HK", "Hong Kong"], 
      ["HM", "Heard Island and McDonald Islands"], 
      ["HN", "Honduras"], 
      ["HR", "Croatia"], 
      ["HT", "Haiti"], 
      ["HU", "Hungary"], 
      ["ID", "Indonesia"], 
      ["IE", "Ireland"], 
      ["IL", "Israel"], 
      ["IM", "Isle of Man"], 
      ["IN", "India"], 
      ["IO", "British Indian Ocean Territory"], 
      ["IQ", "Iraq"], 
      ["IR", "Iran, Islamic Republic of"], 
      ["IS", "Iceland"], 
      ["IT", "Italy"], 
      ["JE", "Jersey"], 
      ["JM", "Jamaica"], 
      ["JO", "Jordan"], 
      ["JP", "Japan"], 
      ["KE", "Kenya"], 
      ["KG", "Kyrgyzstan"], 
      ["KH", "Cambodia"], 
      ["KI", "Kiribati"], 
      ["KM", "Comoros"], 
      ["KN", "Saint Kitts and Nevis"], 
      ["KP", "Korea, Democratic People's Republic of"], 
      ["KR", "Korea, Republic of"], 
      ["KW", "Kuwait"], 
      ["KY", "Cayman Islands"], 
      ["KZ", "Kazakhstan"], 
      ["LA", "Lao People's Democratic Republic"], 
      ["LB", "Lebanon"], 
      ["LC", "Saint Lucia"], 
      ["LI", "Liechtenstein"], 
      ["LK", "Sri Lanka"], 
      ["LR", "Liberia"], 
      ["LS", "Lesotho"], 
      ["LT", "Lithuania"], 
      ["LU", "Luxembourg"], 
      ["LV", "Latvia"], 
      ["LY", "Libya"], 
      ["MA", "Morocco"], 
      ["MC", "Monaco"], 
      ["MD", "Moldova, Republic of"], 
      ["ME", "Montenegro"], 
      ["MF", "Saint Martin (French part)"], 
      ["MG", "Madagascar"], 
      ["MH", "Marshall Islands"], 
      ["MK", "North Macedonia"], 
      ["ML", "Mali"], 
      ["MM", "Myanmar"], 
      ["MN", "Mongolia"], 
      ["MO", "Macao"], 
      ["MP", "Northern Mariana Islands"], 
      ["MQ", "Martinique"], 
      ["MR", "Mauritania"], 
      ["MS", "Montserrat"], 
      ["MT", "Malta"], 
      ["MU", "Mauritius"], 
      ["MV", "Maldives"], 
      ["MW", "Malawi"], 
      ["MX", "Mexico"], 
      ["MY", "Malaysia"], 
      ["MZ", "Mozambique"], 
      ["NA", "Namibia"], 
      ["NC", "New Caledonia"], 
      ["NE", "Niger"], 
      ["NF", "Norfolk Island"], 
      ["NG", "Nigeria"], 
      ["NI", "Nicaragua"], 
      ["NL", "Netherlands, Kingdom of the"], 
      ["NO", "Norway"], 
      ["NP", "Nepal"], 
      ["NR", "Nauru"], 
      ["NU", "Niue"], 
      ["NZ", "New Zealand"], 
      ["OM", "Oman"], 
      ["PA", "Panama"], 
      ["PE", "Peru"], 
      ["PF", "French Polynesia"], 
      ["PG", "Papua New Guinea"], 
      ["PH", "Philippines"], 
      ["PK", "Pakistan"], 
      ["PL", "Poland"], 
      ["PM", "Saint Pierre and Miquelon"], 
      ["PN", "Pitcairn"], 
      ["PR", "Puerto Rico"], 
      ["PS", "Palestine, State of"], 
      ["PT", "Portugal"], 
      ["PW", "Palau"], 
      ["PY", "Paraguay"], 
      ["QA", "Qatar"], 
      ["RE", "RÃ©union"], 
      ["RO", "Romania"], 
      ["RS", "Serbia"], 
      ["RU", "Russian Federation"], 
      ["RW", "Rwanda"], 
      ["SA", "Saudi Arabia"], 
      ["SB", "Solomon Islands"], 
      ["SC", "Seychelles"], 
      ["SD", "Sudan"], 
      ["SE", "Sweden"], 
      ["SG", "Singapore"], 
      ["SH", "Saint Helena, Ascension and Tristan da Cunha"], 
      ["SI", "Slovenia"], 
      ["SJ", "Svalbard and Jan Mayen"], 
      ["SK", "Slovakia"], 
      ["SL", "Sierra Leone"], 
      ["SM", "San Marino"], 
      ["SN", "Senegal"], 
      ["SO", "Somalia"], 
      ["SR", "Suriname"], 
      ["SS", "South Sudan"], 
      ["ST", "Sao Tome and Principe"], 
      ["SV", "El Salvador"], 
      ["SX", "Sint Maarten (Dutch part)"], 
      ["SY", "Syrian Arab Republic"], 
      ["SZ", "Eswatini"], 
      ["TC", "Turks and Caicos Islands"], 
      ["TD", "Chad"], 
      ["TF", "French Southern Territories"], 
      ["TG", "Togo"], 
      ["TH", "Thailand"], 
      ["TJ", "Tajikistan"], 
      ["TK", "Tokelau"], 
      ["TL", "Timor-Leste"], 
      ["TM", "Turkmenistan"], 
      ["TN", "Tunisia"], 
      ["TO", "Tonga"], 
      ["TR", "TÃ¼rkiye"], 
      ["TT", "Trinidad and Tobago"], 
      ["TV", "Tuvalu"], 
      ["TW", "Taiwan, Province of China"], 
      ["TZ", "Tanzania, United Republic of"], 
      ["UA", "Ukraine"], 
      ["UG", "Uganda"], 
      ["UM", "United States Minor Outlying Islands"], 
      ["US", "United States of America"], 
      ["UY", "Uruguay"], 
      ["UZ", "Uzbekistan"], 
      ["VA", "Holy See"], 
      ["VC", "Saint Vincent and the Grenadines"], 
      ["VE", "Venezuela, Bolivarian Republic of"], 
      ["VG", "Virgin Islands (British)"], 
      ["VI", "Virgin Islands (U.S.)"], 
      ["VN", "Viet Nam"], 
      ["VU", "Vanuatu"], 
      ["WF", "Wallis and Futuna"], 
      ["WS", "Samoa"], 
      ["YE", "Yemen"], 
      ["YT", "Mayotte"], 
      ["ZA", "South Africa"], 
      ["ZM", "Zambia"], 
      ["ZW", "Zimbabwe"]      
    ]);

    public static readonly isoCurrencyCodeNames: Map<string, string> = new Map([
      ["AED", "UAE Dirham"], 
      ["AFN", "Afghani"], 
      ["ALL", "Lek"], 
      ["AMD", "Armenian Dram"], 
      ["ANG", "Netherlands Antillean Guilder"], 
      ["AOA", "Kwanza"], 
      ["ARS", "Argentine Peso"], 
      ["AUD", "Australian Dollar"], 
      ["AWG", "Aruban Florin"], 
      ["AZN", "Azerbaijanian Manat"], 
      ["BAM", "Convertible Mark"], 
      ["BBD", "Barbados Dollar"], 
      ["BDT", "Taka"], 
      ["BGN", "Bulgarian Lev"], 
      ["BHD", "Bahraini Dinar"], 
      ["BIF", "Burundi Franc"], 
      ["BMD", "Bermudian Dollar"], 
      ["BND", "Brunei Dollar"], 
      ["BOB", "Boliviano"], 
      ["BOV", "Mvdol"], 
      ["BRL", "Brazilian Real"], 
      ["BSD", "Bahamian Dollar"], 
      ["BTN", "Ngultrum"], 
      ["BWP", "Pula"], 
      ["BYN", "Belarussian Ruble"], 
      ["BZD", "Belize Dollar"], 
      ["CAD", "Canadian Dollar"], 
      ["CDF", "Congolese Franc"], 
      ["CHE", "WIR Euro"], 
      ["CHF", "Swiss Franc"], 
      ["CHW", "WIR Franc"], 
      ["CLF", "Unidad de Fomento"], 
      ["CLP", "Chilean Peso"], 
      ["CNY", "Yuan Renminbi"], 
      ["COP", "Colombian Peso"], 
      ["COU", "Unidad de Valor Real"], 
      ["CRC", "Costa Rican Colon"], 
      ["CUC", "Peso Convertible"], 
      ["CUP", "Cuban Peso"], 
      ["CVE", "Cabo Verde Escudo"], 
      ["CZK", "Czech Koruna"], 
      ["DJF", "Djibouti Franc"], 
      ["DKK", "Danish Krone"], 
      ["DOP", "Dominican Peso"], 
      ["DZD", "Algerian Dinar"], 
      ["EGP", "Egyptian Pound"], 
      ["ERN", "Nakfa"], 
      ["ETB", "Ethiopian Birr"], 
      ["EUR", "Euro"], 
      ["FJD", "Fiji Dollar"], 
      ["FKP", "Falkland Islands Pound"], 
      ["GBP", "Pound Sterling"], 
      ["GEL", "Lari"], 
      ["GHS", "Ghana Cedi"], 
      ["GIP", "Gibraltar Pound"], 
      ["GMD", "Dalasi"], 
      ["GNF", "Guinea Franc"], 
      ["GTQ", "Quetzal"], 
      ["GYD", "Guyana Dollar"], 
      ["HKD", "Hong Kong Dollar"], 
      ["HNL", "Lempira"], 
      ["HTG", "Gourde"], 
      ["HUF", "Forint"], 
      ["IDR", "Rupiah"], 
      ["ILS", "New Israeli Sheqel"], 
      ["INR", "Indian Rupee"], 
      ["IQD", "Iraqi Dinar"], 
      ["IRR", "Iranian Rial"], 
      ["ISK", "Iceland Krona"], 
      ["JMD", "Jamaican Dollar"], 
      ["JOD", "Jordanian Dinar"], 
      ["JPY", "Yen"], 
      ["KES", "Kenyan Shilling"], 
      ["KGS", "Som"], 
      ["KHR", "Riel"], 
      ["KMF", "Comoro Franc"], 
      ["KPW", "North Korean Won"], 
      ["KRW", "Won"], 
      ["KWD", "Kuwaiti Dinar"], 
      ["KYD", "Cayman Islands Dollar"], 
      ["KZT", "Tenge"], 
      ["LAK", "Kip"], 
      ["LBP", "Lebanese Pound"], 
      ["LKR", "Sri Lanka Rupee"], 
      ["LRD", "Liberian Dollar"], 
      ["LSL", "Loti"], 
      ["LYD", "Libyan Dinar"], 
      ["MAD", "Moroccan Dirham"], 
      ["MDL", "Moldovan Leu"], 
      ["MGA", "Malagasy Ariary"], 
      ["MKD", "Denar"], 
      ["MMK", "Kyat"], 
      ["MNT", "Tugrik"], 
      ["MOP", "Pataca"], 
      ["MRU", "Ouguiya"], 
      ["MUR", "Mauritius Rupee"], 
      ["MVR", "Rufiyaa"], 
      ["MWK", "Kwacha"], 
      ["MXN", "Mexican Peso"], 
      ["MXV", "Mexican Unidad de Inversion (UDI)"], 
      ["MYR", "Malaysian Ringgit"], 
      ["MZN", "Mozambique Metical"], 
      ["NAD", "Namibia Dollar"], 
      ["NGN", "Naira"], 
      ["NIO", "Cordoba Oro"], 
      ["NOK", "Norwegian Krone"], 
      ["NPR", "Nepalese Rupee"], 
      ["NZD", "New Zealand Dollar"], 
      ["OMR", "Rial Omani"], 
      ["PAB", "Balboa"], 
      ["PEN", "Nuevo Sol"], 
      ["PGK", "Kina"], 
      ["PHP", "Philippine Peso"], 
      ["PKR", "Pakistan Rupee"], 
      ["PLN", "Zloty"], 
      ["PYG", "Guarani"], 
      ["QAR", "Qatari Rial"], 
      ["RON", "Romanian Leu"], 
      ["RSD", "Serbian Dinar"], 
      ["RUB", "Russian Ruble"], 
      ["RWF", "Rwanda Franc"], 
      ["SAR", "Saudi Riyal"], 
      ["SBD", "Solomon Islands Dollar"], 
      ["SCR", "Seychelles Rupee"], 
      ["SDG", "Sudanese Pound"], 
      ["SEK", "Swedish Krona"], 
      ["SGD", "Singapore Dollar"], 
      ["SHP", "Saint Helena Pound"], 
      ["SLE", "Leone"], 
      ["SOS", "Somali Shilling"], 
      ["SRD", "Surinam Dollar"], 
      ["SSP", "South Sudanese Pound"], 
      ["STN", "Dobra"], 
      ["SVC", "El Salvador Colon"], 
      ["SYP", "Syrian Pound"], 
      ["SZL", "Lilangeni"], 
      ["THB", "Baht"], 
      ["TJS", "Somoni"], 
      ["TMT", "Turkmenistan New Manat"], 
      ["TND", "Tunisian Dinar"], 
      ["TOP", "Pa’anga"], 
      ["TRY", "Turkish Lira"], 
      ["TTD", "Trinidad and Tobago Dollar"], 
      ["TWD", "New Taiwan Dollar"], 
      ["TZS", "Tanzanian Shilling"], 
      ["UAH", "Hryvnia"], 
      ["UGX", "Uganda Shilling"], 
      ["USD", "US Dollar"], 
      ["USN", "US Dollar (Next day)"], 
      ["UYI", "Uruguay Peso en Unidades Indexadas (URUIURUI)"], 
      ["UYU", "Peso Uruguayo"], 
      ["UZS", "Uzbekistan Sum"], 
      ["VED", "Bolivar"], 
      ["VEF", "Bolivar"], 
      ["VND", "Dong"], 
      ["VUV", "Vatu"], 
      ["WST", "Tala"], 
      ["XAF", "CFA Franc BEAC"], 
      ["XCD", "East Caribbean Dollar"], 
      ["XDR", "SDR (Special Drawing Right)"], 
      ["XOF", "CFA Franc BCEAO"], 
      ["XPF", "CFP Franc"], 
      ["XSU", "Sucre"], 
      ["XUA", "ADB Unit of Account"], 
      ["YER", "Yemeni Rial"], 
      ["ZAR", "Rand"], 
      ["ZMW", "Zambian Kwacha"], 
      ["ZWL", "Zimbabwe Dollar"]      
    ]);

    /*
'1' - Foreign Exchange Rate: This value means the Foreign Exchange Reference field contains the actual foreign exchange rate applied to the transaction. This rate is used to convert currency from one denomination to another in cases where currency conversion is part of the transaction.

'2' - Foreign Exchange Reference Number: When this value is used, the Foreign Exchange Reference field will contain a reference number related to the foreign exchange transaction. This could be an identifier from a foreign exchange service provider, helping to link the IAT entry with specific foreign exchange records.

'3' - Space Filled: This value indicates that no foreign exchange information is provided in the Foreign Exchange Reference field. It's typically used when no currency conversion is involved, meaning the amount remains the same across both originating and receiving currencies. 
    */
    public static readonly foreignExchangeReferenceIndicatorCodes: Map<number, string> = new Map([
      [1, 'Foreign Exchange Rate'], 
      [2, 'Foreign Exchange Reference Number'],
      [3, 'Space Filled']
    ]);

    public static readonly IATransactionTypeCodes: Map<string, string> = new Map([
      ["ANN", "Annuity"], 
      ["ARC", "Accounts Receivable Entry"], 
      ["BOC", "Back Office Conversion Entry"], 
      ["BUS", "Business/Commercial"], 
      ["DEP", "Deposit"], 
      ["LOA", "Loan"], 
      ["MIS", "Miscellaneous"], 
      ["MOR ", "Mortgage"], 
      ["MTE", "Machine Transfer Entry"], 
      ["PEN", "Pension"], 
      ["POP", "Point of Purchase Entry"], 
      ["POS", "Point of Sale Entry"], 
      ["RCK", "Re-presented Check Entry"], 
      ["REM", "Remittance"], 
      ["RLS", "Rent/Lease"], 
      ["SAL", "Salary/Payroll"], 
      ["SHR", "Shared Network Transaction"], 
      ["TAX", "Tax"], 
      ["TEL", "Telephone-Initiated Entry"], 
      ["WEB", "Internet-Initiated Entry"]      
    ]);


}

export enum RecordType {
    fileHeader          = "1",
    batchHeader         = "5",
    entryDetail         = "6",
    entryDetailAddenda  = "7",
    batchControl        = "8",
    fileControl         = "9"
}
